### ISSUE TITLE
500 error upon submitting a work in deployed QA branch

### ISSUE THREAD

**Issue by Janell-Huyck** [uclibs/aaec#216] opened 2023-09-21 13:50 UTC
When running locally and submitting a work, I end up at the following page:
![Screenshot 2023-09-21 at 9 48 19 AM](https://github.com/uclibs/aaec/assets/57018862/6492952b-5665-4990-9167-145ecf4797cb)
Following the same path along the libappstest.uc.edu gives me a 500 error:
![Screenshot 2023-09-21 at 9 49 22 AM](https://github.com/uclibs/aaec/assets/57018862/241b9d01-b147-492b-9c65-26f4deec78dc)
Discover why we get a 500 error upon submitting a work in qa and resolve it.

**Comment by haitzlm** [comment] 2023-09-21 14:42
the urls are different in the two examples. The working one is /publications, and the non-working one is /other_publications

**Comment by hortongn** [comment] 2023-09-21 14:57
@Janell-Huyck I think this issue is a duplicate of #162.  The problem may only exist on our servers.

If you'd like the app to show detailed error pages on libappstest, you can temporarily change https://github.com/uclibs/aaec/blob/qa/config/environments/production.rb#L16 to `true` and deploy the branch.  You'll see error pages just like you do on your machine.

**Comment by Janell-Huyck** [comment] 2023-09-21 15:32
> the urls are different in the two examples. The working one is /publications, and the non-working one is /other_publications

True, but I got the same result either way.  other_publications is another kind of publication, "Other".  It works fine in local, and errors in deploy.

**Closed** 2023-09-21 15:33 UTC
